module Test {
    struct Flat {
        long a;
        bool b;
        string c;
        bool d;
        long long e;
        bool f;
        short g;
        char h;
        string i;
        short j;
    };
    struct Nested {
        Flat a;
        bool b;
        Flat c;
        short d;
        Flat e;
        long f;
        Flat g;
        bool h;
    };
    struct 
};
